"""Generated immutable structural views for local-Hermes contract v1.

Regenerate with ``python -m thine_harness.contracts._codegen`` after accepting
a new contract pack version. Do not edit this file by hand.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Literal, Protocol

from ._base import FrozenJSONValue


class RuntimeActionIntentVariant1View(Protocol):
    @property
    def kind(self) -> Literal["background_message"] | None: ...

    @property
    def safe_payload(
        self,
    ) -> RuntimeRuntimeActionIntentVariant1SafePayloadView | None: ...


class RuntimeActionIntentVariant2View(Protocol):
    @property
    def kind(self) -> Literal["standalone_notification"] | None: ...

    @property
    def safe_payload(
        self,
    ) -> RuntimeRuntimeActionIntentVariant2SafePayloadView | None: ...


class RuntimeActionIntentVariant3View(Protocol):
    @property
    def kind(self) -> Literal["home_mutation"] | None: ...

    @property
    def safe_payload(
        self,
    ) -> RuntimeRuntimeActionIntentVariant3SafePayloadView | None: ...


class RuntimeActionIntentVariant4View(Protocol):
    @property
    def kind(self) -> Literal["schedule_create"] | None: ...

    @property
    def safe_payload(
        self,
    ) -> RuntimeRuntimeActionIntentVariant4SafePayloadView | None: ...


class RuntimeActionIntentVariant5View(Protocol):
    @property
    def kind(self) -> Literal["preference_change"] | None: ...

    @property
    def safe_payload(
        self,
    ) -> RuntimeRuntimeActionIntentVariant5SafePayloadView | None: ...


class RuntimeActionReceiptView(Protocol):
    @property
    def schema_version(self) -> RuntimeVersionView: ...

    @property
    def receipt_id(self) -> str: ...

    @property
    def action_identity(self) -> RuntimeRuntimeActionReceiptActionIdentityView: ...

    @property
    def status(self) -> Literal["succeeded", "failed_terminal", "queued_for_retry"]: ...

    @property
    def provider_correlation_id(self) -> str | None: ...

    @property
    def accepted_at_ms(self) -> int | None: ...

    @property
    def reconciliation_state(
        self,
    ) -> Literal[
        "not_needed", "pending", "confirmed_applied", "confirmed_not_applied"
    ]: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class RuntimeAttemptView(Protocol):
    @property
    def schema_version(self) -> RuntimeVersionView: ...

    @property
    def attempt_id(self) -> str: ...

    @property
    def logical_run_id(self) -> str: ...

    @property
    def ordinal(self) -> int: ...

    @property
    def cause(self) -> Literal["initial", "fault_retry"]: ...

    @property
    def status(self) -> Literal["running", "succeeded", "failed_fault"]: ...

    @property
    def started_at_ms(self) -> int: ...

    @property
    def finished_at_ms(self) -> int | None: ...

    @property
    def failure_code(self) -> str | None: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class RuntimeCheckpointView(Protocol):
    @property
    def schema_version(self) -> RuntimeVersionView: ...

    @property
    def checkpoint_id(self) -> str: ...

    @property
    def resume_token(self) -> str: ...

    @property
    def logical_run_id(self) -> str: ...

    @property
    def input_reference(self) -> str: ...

    @property
    def remaining_work(self) -> str: ...

    @property
    def context_messages(
        self,
    ) -> tuple[
        RuntimeContextMessageVariant1View
        | RuntimeContextMessageVariant2View
        | RuntimeContextMessageVariant3View,
        ...,
    ]: ...

    @property
    def completed_tool_result_ids(self) -> tuple[str, ...]: ...

    @property
    def successful_action_receipt_ids(self) -> tuple[str, ...]: ...

    @property
    def partial_visible_assistant_output(self) -> str: ...

    @property
    def updated_at_ms(self) -> int: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class RuntimeDashboardReadModelView(Protocol):
    @property
    def schema_version(self) -> RuntimeVersionView: ...

    @property
    def model_id(
        self,
    ) -> Literal[
        "queue",
        "current_run",
        "transcripts",
        "memory",
        "actions",
        "communications",
        "home",
        "schedules",
        "failures",
        "topics",
        "interactions",
        "debug_timeline",
    ]: ...

    @property
    def generated_at_ms(self) -> int: ...

    @property
    def source_state_paths(self) -> tuple[str, ...]: ...

    @property
    def item_count(self) -> int: ...

    @property
    def status(self) -> Literal["ok", "degraded", "unavailable"]: ...

    @property
    def summary_ref(self) -> str | None: ...

    @property
    def authoritative(self) -> Literal[False]: ...

    @property
    def redacted(self) -> Literal[True]: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class RuntimeDashboardSnapshotView(Protocol):
    @property
    def schema_version(self) -> RuntimeVersionView: ...

    @property
    def snapshot_id(self) -> str: ...

    @property
    def generated_at_ms(self) -> int: ...

    @property
    def binding(self) -> Literal["mac_loopback_only"]: ...

    @property
    def authoritative(self) -> Literal[False]: ...

    @property
    def read_models(self) -> tuple[RuntimeDashboardReadModelView, ...]: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class RuntimeExplicitRetryView(Protocol):
    @property
    def schema_version(self) -> RuntimeVersionView: ...

    @property
    def retry_run_id(self) -> str: ...

    @property
    def quarantine_id(self) -> str: ...

    @property
    def source_identity(self) -> str: ...

    @property
    def preserved_receipt_ids(self) -> tuple[str, ...]: ...

    @property
    def created_at_ms(self) -> int: ...

    @property
    def rewinds_normal_cursor(self) -> Literal[False]: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class RuntimeFinalReplyOutboxVariant1View(Protocol):
    @property
    def status(self) -> Literal["pending_backend_persistence"] | None: ...

    @property
    def backend_receipt_id(self) -> None: ...


class RuntimeFinalReplyOutboxVariant2View(Protocol):
    @property
    def status(self) -> Literal["persisted"] | None: ...

    @property
    def backend_receipt_id(self) -> str | None: ...


class RuntimeFinalReplyReceiptView(Protocol):
    @property
    def schema_version(self) -> RuntimeVersionView: ...

    @property
    def receipt_id(self) -> str: ...

    @property
    def assistant_message_id(self) -> str: ...

    @property
    def user_message_id(self) -> str: ...

    @property
    def backend_message_id(self) -> str: ...

    @property
    def idempotency_key(self) -> str: ...

    @property
    def resolution(self) -> Literal["persisted_now", "existing_receipt"]: ...

    @property
    def persisted_at_ms(self) -> int: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class RuntimeHermesControlRequestVariant1View(Protocol):
    @property
    def operation(
        self,
    ) -> Literal["submit_p0", "append_interactions", "cancel"] | None: ...

    @property
    def payload_ref(self) -> str | None: ...


class RuntimeHermesControlRequestVariant2View(Protocol):
    @property
    def operation(self) -> Literal["get_home", "health", "get_status"] | None: ...

    @property
    def payload_ref(self) -> None: ...


class RuntimeHermesControlResponseVariant1View(Protocol):
    @property
    def status(self) -> Literal["succeeded"] | None: ...

    @property
    def result_ref(self) -> str | None: ...

    @property
    def error_code(self) -> None: ...


class RuntimeHermesControlResponseVariant2View(Protocol):
    @property
    def status(self) -> Literal["timed_out", "rejected"] | None: ...

    @property
    def result_ref(self) -> None: ...

    @property
    def error_code(self) -> str | None: ...


class RuntimeInputReceiptView(Protocol):
    @property
    def schema_version(self) -> RuntimeVersionView: ...

    @property
    def receipt_id(self) -> str: ...

    @property
    def source_kind(
        self,
    ) -> Literal["transcript", "speaker_mapping", "interaction"]: ...

    @property
    def source_identity(self) -> str: ...

    @property
    def logical_run_id(self) -> str: ...

    @property
    def ack_id(self) -> str: ...

    @property
    def disposition(self) -> Literal["acknowledged", "quarantined"]: ...

    @property
    def recorded_at_ms(self) -> int: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class RuntimeInteractionCursorConsumptionReceiptView(Protocol):
    @property
    def schema_version(self) -> RuntimeVersionView: ...

    @property
    def consumption_receipt_id(self) -> str: ...

    @property
    def batch_id(self) -> str: ...

    @property
    def first_cursor(self) -> int: ...

    @property
    def last_cursor(self) -> int: ...

    @property
    def logical_run_id(self) -> str: ...

    @property
    def finalization_id(self) -> str: ...

    @property
    def consumed_cursor(self) -> int: ...

    @property
    def consumed_at_ms(self) -> int: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class RuntimeInvocationEventVariant1View(Protocol):
    @property
    def kind(self) -> Literal["accepted", "started", "progress"] | None: ...

    @property
    def ephemeral(self) -> Literal[True] | None: ...

    @property
    def result_ref(self) -> None: ...

    @property
    def error_code(self) -> None: ...

    @property
    def usage(self) -> None: ...

    @property
    def resume_token(self) -> None: ...


class RuntimeInvocationEventVariant2View(Protocol):
    @property
    def kind(self) -> Literal["final"] | None: ...

    @property
    def ephemeral(self) -> Literal[False] | None: ...

    @property
    def result_ref(self) -> str | None: ...

    @property
    def error_code(self) -> None: ...

    @property
    def usage(self) -> Mapping[str, FrozenJSONValue] | None: ...

    @property
    def resume_token(self) -> None: ...


class RuntimeInvocationEventVariant3View(Protocol):
    @property
    def kind(self) -> Literal["failed"] | None: ...

    @property
    def ephemeral(self) -> Literal[False] | None: ...

    @property
    def result_ref(self) -> None: ...

    @property
    def error_code(self) -> str | None: ...

    @property
    def usage(self) -> Mapping[str, FrozenJSONValue] | None: ...

    @property
    def resume_token(self) -> None: ...


class RuntimeInvocationEventVariant4View(Protocol):
    @property
    def kind(self) -> Literal["interrupted"] | None: ...

    @property
    def ephemeral(self) -> Literal[False] | None: ...

    @property
    def result_ref(self) -> None: ...

    @property
    def error_code(self) -> str | None: ...

    @property
    def usage(self) -> Mapping[str, FrozenJSONValue] | None: ...

    @property
    def resume_token(self) -> str | None: ...


class RuntimeInvocationRequestView(Protocol):
    @property
    def schema_version(self) -> RuntimeVersionView: ...

    @property
    def invocation_id(self) -> str: ...

    @property
    def logical_run_id(self) -> str: ...

    @property
    def tick_id(self) -> str: ...

    @property
    def mode(self) -> Literal["new", "resumed"]: ...

    @property
    def kind(
        self,
    ) -> Literal[
        "p0_user_chat", "p1_transcript", "p1_speaker", "p1_interaction", "p2_scheduled"
    ]: ...

    @property
    def prompt(self) -> str: ...

    @property
    def prompt_token_count(self) -> int: ...

    @property
    def input_ref(self) -> RuntimeInvocationReferenceView: ...

    @property
    def source_ref(self) -> RuntimeInvocationReferenceView: ...

    @property
    def resume_token(self) -> str | None: ...

    @property
    def checkpoint_id(self) -> str | None: ...

    @property
    def context_messages(
        self,
    ) -> tuple[
        RuntimeContextMessageVariant1View
        | RuntimeContextMessageVariant2View
        | RuntimeContextMessageVariant3View,
        ...,
    ]: ...

    @property
    def completed_tool_result_ids(self) -> tuple[str, ...]: ...

    @property
    def successful_action_receipt_ids(self) -> tuple[str, ...]: ...

    @property
    def partial_visible_assistant_output(self) -> str: ...

    @property
    def input_gap_ids(self) -> tuple[str, ...]: ...

    @property
    def runtime_diagnostics(self) -> RuntimeRuntimeDiagnosticsView: ...

    @property
    def requested_at_ms(self) -> int: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class RuntimeP0SubmissionOutboxVariant1View(Protocol):
    @property
    def status(self) -> Literal["received"] | None: ...

    @property
    def queue_receipt_id(self) -> None: ...

    @property
    def cancellable(self) -> Literal[True] | None: ...


class RuntimeP0SubmissionOutboxVariant2View(Protocol):
    @property
    def status(self) -> Literal["enqueued"] | None: ...

    @property
    def queue_receipt_id(self) -> str | None: ...

    @property
    def cancellable(self) -> Literal[False] | None: ...


class RuntimeP0SubmissionOutboxVariant3View(Protocol):
    @property
    def status(self) -> Literal["cancelled"] | None: ...

    @property
    def queue_receipt_id(self) -> None: ...

    @property
    def cancellable(self) -> Literal[False] | None: ...


class RuntimeQuarantineRecordVariant1View(Protocol):
    @property
    def source_kind(self) -> Literal["transcript"] | None: ...

    @property
    def immutable_range(
        self,
    ) -> RuntimeRuntimeQuarantineRecordVariant1ImmutableRangeView | None: ...

    @property
    def normal_cursor_advanced(self) -> Literal[True] | None: ...


class RuntimeQuarantineRecordVariant2View(Protocol):
    @property
    def source_kind(self) -> Literal["speaker_mapping"] | None: ...

    @property
    def immutable_range(
        self,
    ) -> RuntimeRuntimeQuarantineRecordVariant2ImmutableRangeView | None: ...

    @property
    def normal_cursor_advanced(self) -> Literal[True] | None: ...


class RuntimeQuarantineRecordVariant3View(Protocol):
    @property
    def source_kind(self) -> Literal["interaction"] | None: ...

    @property
    def immutable_range(
        self,
    ) -> RuntimeRuntimeQuarantineRecordVariant3ImmutableRangeView | None: ...

    @property
    def normal_cursor_advanced(self) -> Literal[True] | None: ...


class RuntimeQuarantineRecordVariant4View(Protocol):
    @property
    def source_kind(self) -> Literal["scheduled"] | None: ...

    @property
    def immutable_range(self) -> None: ...

    @property
    def normal_cursor_advanced(self) -> Literal[False] | None: ...


class RuntimeQueueReceiptView(Protocol):
    @property
    def schema_version(self) -> RuntimeVersionView: ...

    @property
    def receipt_id(self) -> str: ...

    @property
    def user_id(self) -> str: ...

    @property
    def user_message_id(self) -> str: ...

    @property
    def idempotency_key(self) -> str: ...

    @property
    def logical_run_id(self) -> str: ...

    @property
    def tick_id(self) -> str: ...

    @property
    def resolution(self) -> Literal["enqueued_now", "existing_receipt"]: ...

    @property
    def enqueued_at_ms(self) -> int: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class RuntimeResetCommandView(Protocol):
    @property
    def schema_version(self) -> RuntimeVersionView: ...

    @property
    def reset_id(self) -> str: ...

    @property
    def scope(
        self,
    ) -> Literal[
        "working_memory_topics",
        "queues_schedules_receipts",
        "home_state",
        "all_hermes_state",
    ]: ...

    @property
    def confirmed(self) -> bool: ...

    @property
    def confirmed_preferences_revision(self) -> int | None: ...

    @property
    def current_preferences_revision(self) -> int | None: ...

    @property
    def explicit_preferences_to_delete(
        self,
    ) -> tuple[RuntimeRuntimeResetCommandExplicitPreferencesToDeleteItemView, ...]: ...

    @property
    def execute(self) -> bool: ...

    @property
    def harness_stopped(self) -> bool: ...

    @property
    def live_work_count(self) -> int: ...

    @property
    def requested_at_ms(self) -> int: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class RuntimeResetResultVariant1View(Protocol):
    @property
    def status(self) -> Literal["completed"] | None: ...

    @property
    def execution_requested(self) -> Literal[True] | None: ...

    @property
    def preconditions_satisfied(self) -> Literal[True] | None: ...

    @property
    def completed_at_ms(self) -> int | None: ...


class RuntimeResetResultVariant2View(Protocol):
    @property
    def status(self) -> Literal["refused_live_work"] | None: ...

    @property
    def execution_requested(self) -> Literal[True] | None: ...

    @property
    def preconditions_satisfied(self) -> Literal[False] | None: ...

    @property
    def completed_at_ms(self) -> None: ...


class RuntimeResetResultVariant3View(Protocol):
    @property
    def status(self) -> Literal["confirmation_required"] | None: ...

    @property
    def execution_requested(self) -> Literal[False] | None: ...

    @property
    def preconditions_satisfied(self) -> Literal[False] | None: ...

    @property
    def completed_at_ms(self) -> None: ...


class RuntimeRunFinalizationVariant1View(Protocol):
    @property
    def tick_kind(self) -> Literal["p0_user_chat"] | None: ...

    @property
    def phase(self) -> Literal["reply_delivery_pending"] | None: ...

    @property
    def source_ack_id(self) -> None: ...

    @property
    def final_reply_receipt_id(self) -> None: ...

    @property
    def recovery_mode(self) -> Literal["ack_only"] | None: ...

    @property
    def finalized_at_ms(self) -> None: ...


class RuntimeRunFinalizationVariant2View(Protocol):
    @property
    def tick_kind(self) -> Literal["p0_user_chat"] | None: ...

    @property
    def phase(self) -> Literal["reply_persisted"] | None: ...

    @property
    def source_ack_id(self) -> None: ...

    @property
    def final_reply_receipt_id(self) -> str | None: ...

    @property
    def recovery_mode(self) -> Literal["hook_only"] | None: ...

    @property
    def finalized_at_ms(self) -> None: ...


class RuntimeRunFinalizationVariant3View(Protocol):
    @property
    def tick_kind(self) -> Literal["p0_user_chat"] | None: ...

    @property
    def phase(self) -> Literal["memory_finalization_pending"] | None: ...

    @property
    def source_ack_id(self) -> None: ...

    @property
    def final_reply_receipt_id(self) -> str | None: ...

    @property
    def recovery_mode(self) -> Literal["hook_only"] | None: ...

    @property
    def finalized_at_ms(self) -> None: ...


class RuntimeRunFinalizationVariant4View(Protocol):
    @property
    def tick_kind(self) -> Literal["p0_user_chat"] | None: ...

    @property
    def phase(self) -> Literal["completed"] | None: ...

    @property
    def source_ack_id(self) -> None: ...

    @property
    def final_reply_receipt_id(self) -> str | None: ...

    @property
    def recovery_mode(self) -> Literal["normal", "hook_only"] | None: ...

    @property
    def finalized_at_ms(self) -> int | None: ...


class RuntimeRunFinalizationVariant5View(Protocol):
    @property
    def tick_kind(self) -> Literal["p1_transcript"] | None: ...

    @property
    def phase(self) -> Literal["awaiting_audio_ack"] | None: ...

    @property
    def source_ack_id(self) -> None: ...

    @property
    def final_reply_receipt_id(self) -> None: ...

    @property
    def recovery_mode(self) -> Literal["ack_only"] | None: ...

    @property
    def finalized_at_ms(self) -> None: ...


class RuntimeRunFinalizationVariant6View(Protocol):
    @property
    def tick_kind(self) -> Literal["p1_speaker"] | None: ...

    @property
    def phase(self) -> Literal["awaiting_speaker_cursor_ack"] | None: ...

    @property
    def source_ack_id(self) -> None: ...

    @property
    def final_reply_receipt_id(self) -> None: ...

    @property
    def recovery_mode(self) -> Literal["ack_only"] | None: ...

    @property
    def finalized_at_ms(self) -> None: ...


class RuntimeRunFinalizationVariant7View(Protocol):
    @property
    def tick_kind(
        self,
    ) -> Literal["p1_transcript", "p1_speaker", "p1_interaction"] | None: ...

    @property
    def phase(self) -> Literal["completed"] | None: ...

    @property
    def source_ack_id(self) -> str | None: ...

    @property
    def final_reply_receipt_id(self) -> None: ...

    @property
    def recovery_mode(self) -> Literal["normal", "ack_only"] | None: ...

    @property
    def finalized_at_ms(self) -> int | None: ...


class RuntimeRunFinalizationVariant8View(Protocol):
    @property
    def tick_kind(self) -> Literal["p2_scheduled"] | None: ...

    @property
    def phase(self) -> Literal["completed"] | None: ...

    @property
    def source_ack_id(self) -> None: ...

    @property
    def final_reply_receipt_id(self) -> None: ...

    @property
    def recovery_mode(self) -> Literal["normal"] | None: ...

    @property
    def finalized_at_ms(self) -> int | None: ...


class RuntimeRunReceiptVariant1View(Protocol):
    @property
    def outcome(self) -> Literal["completed"] | None: ...

    @property
    def finalization_id(self) -> str | None: ...


class RuntimeRunReceiptVariant2View(Protocol):
    @property
    def outcome(self) -> Literal["failed_terminal", "quarantined"] | None: ...

    @property
    def attempts_total(self) -> Literal[3] | None: ...

    @property
    def finalization_id(self) -> None: ...


class RuntimeStopHookDecisionVariant1View(Protocol):
    @property
    def outcome(self) -> Literal["committed"] | None: ...

    @property
    def worth_remembering(self) -> Literal[True] | None: ...

    @property
    def memory_write_performed(self) -> Literal[True] | None: ...

    @property
    def tokenizer_status(self) -> Literal["exact"] | None: ...

    @property
    def configured_model_token_count(self) -> int | None: ...


class RuntimeStopHookDecisionVariant2View(Protocol):
    @property
    def outcome(self) -> Literal["unchanged", "skipped_interrupted"] | None: ...

    @property
    def worth_remembering(self) -> Literal[False] | None: ...

    @property
    def memory_write_performed(self) -> Literal[False] | None: ...


class RuntimeTickVariant1View(Protocol):
    @property
    def kind(self) -> Literal["p0_user_chat"] | None: ...

    @property
    def priority(self) -> Literal["p0"] | None: ...

    @property
    def source_ref(self) -> RuntimeRuntimeTickVariant1SourceRefView | None: ...

    @property
    def payload(self) -> RuntimeRuntimeTickVariant1PayloadView | None: ...


class RuntimeTickVariant2View(Protocol):
    @property
    def kind(self) -> Literal["p1_transcript"] | None: ...

    @property
    def priority(self) -> Literal["p1"] | None: ...

    @property
    def source_ref(self) -> RuntimeRuntimeTickVariant2SourceRefView | None: ...

    @property
    def payload(self) -> RuntimeRuntimeTickVariant2PayloadView | None: ...


class RuntimeTickVariant3View(Protocol):
    @property
    def kind(self) -> Literal["p1_speaker"] | None: ...

    @property
    def priority(self) -> Literal["p1"] | None: ...

    @property
    def source_ref(self) -> RuntimeRuntimeTickVariant3SourceRefView | None: ...

    @property
    def payload(self) -> RuntimeRuntimeTickVariant3PayloadView | None: ...


class RuntimeTickVariant4View(Protocol):
    @property
    def kind(self) -> Literal["p1_interaction"] | None: ...

    @property
    def priority(self) -> Literal["p1"] | None: ...

    @property
    def source_ref(self) -> RuntimeRuntimeTickVariant4SourceRefView | None: ...

    @property
    def payload(self) -> RuntimeRuntimeTickVariant4PayloadView | None: ...


class RuntimeTickVariant5View(Protocol):
    @property
    def kind(self) -> Literal["p2_scheduled"] | None: ...

    @property
    def priority(self) -> Literal["p2", "p1"] | None: ...

    @property
    def source_ref(self) -> RuntimeRuntimeTickVariant5SourceRefView | None: ...

    @property
    def payload(self) -> RuntimeRuntimeTickVariant5PayloadView | None: ...


class RuntimeToolResultVariant1View(Protocol):
    @property
    def status(self) -> Literal["queued_for_reconciliation"] | None: ...

    @property
    def effect_disposition(self) -> Literal["unknown"] | None: ...

    @property
    def timed_out(self) -> Literal[True] | None: ...

    @property
    def reconciliation(self) -> Literal["pending"] | None: ...


class RuntimeToolResultVariant2View(Protocol):
    @property
    def status(
        self,
    ) -> Literal["succeeded", "failed_retryable", "failed_terminal"] | None: ...

    @property
    def timed_out(self) -> Literal[False] | None: ...

    @property
    def reconciliation(
        self,
    ) -> Literal["not_needed", "confirmed_applied", "confirmed_not_applied"] | None: ...


class RuntimeTopicLifecycleVariant1View(Protocol):
    @property
    def state(self) -> Literal["proposed"] | None: ...

    @property
    def last_asked_at_ms(self) -> None: ...


class RuntimeTopicLifecycleVariant2View(Protocol):
    @property
    def state(
        self,
    ) -> Literal["asked", "acknowledged", "snoozed", "resolved", "expired"] | None: ...

    @property
    def last_asked_at_ms(self) -> int | None: ...


class RuntimeWorkingMemorySnapshotView(Protocol):
    @property
    def schema_version(self) -> RuntimeVersionView: ...

    @property
    def user_id(self) -> str: ...

    @property
    def version(self) -> int: ...

    @property
    def markdown(self) -> str: ...

    @property
    def configured_model_token_count(self) -> int | None: ...

    @property
    def tokenizer_status(self) -> Literal["exact", "unresolved_fail_closed"]: ...

    @property
    def max_tokens(self) -> Literal[16000]: ...

    @property
    def debug_retention_versions(self) -> Literal[50]: ...

    @property
    def restorable(self) -> Literal[False]: ...

    @property
    def committed_at_ms(self) -> int: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class RuntimeContextMessageVariant1View(Protocol):
    @property
    def role(self) -> Literal["user"]: ...

    @property
    def message_id(self) -> str: ...

    @property
    def content(self) -> str: ...


class RuntimeContextMessageVariant2View(Protocol):
    @property
    def role(self) -> Literal["assistant"]: ...

    @property
    def message_id(self) -> str: ...

    @property
    def content(self) -> str: ...


class RuntimeContextMessageVariant3View(Protocol):
    @property
    def role(self) -> Literal["tool"]: ...

    @property
    def tool_result_id(self) -> str: ...

    @property
    def safe_summary(self) -> str: ...


class RuntimeInvocationReferenceView(Protocol):
    @property
    def kind(
        self,
    ) -> Literal[
        "user_message",
        "transcript_availability",
        "transcript_claim",
        "speaker_mapping_event",
        "interaction_window",
        "interaction_batch",
        "schedule",
        "quarantine_retry",
    ]: ...

    @property
    def id(self) -> str: ...


class RuntimeRuntimeActionIntentVariant1SafePayloadView(Protocol):
    @property
    def payload_kind(self) -> Literal["background_message"] | None: ...


class RuntimeRuntimeActionIntentVariant2SafePayloadView(Protocol):
    @property
    def payload_kind(self) -> Literal["standalone_notification"] | None: ...


class RuntimeRuntimeActionIntentVariant3SafePayloadView(Protocol):
    @property
    def payload_kind(self) -> Literal["home_mutation"] | None: ...


class RuntimeRuntimeActionIntentVariant4SafePayloadView(Protocol):
    @property
    def payload_kind(self) -> Literal["schedule_create"] | None: ...


class RuntimeRuntimeActionIntentVariant5SafePayloadView(Protocol):
    @property
    def payload_kind(self) -> Literal["preference_change"] | None: ...


class RuntimeRuntimeActionReceiptActionIdentityView(Protocol):
    @property
    def action_id(self) -> str: ...

    @property
    def logical_run_id(self) -> str: ...

    @property
    def effect_ordinal(self) -> int: ...

    @property
    def intent_fingerprint(self) -> str: ...


class RuntimeRuntimeDiagnosticsView(Protocol):
    @property
    def provider(self) -> Literal["openai-codex"]: ...

    @property
    def model(self) -> Literal["gpt-5.6-sol"]: ...

    @property
    def api_mode(self) -> Literal["codex_responses"]: ...

    @property
    def reasoning_effort(self) -> Literal["medium"]: ...

    @property
    def context_window_tokens(self) -> Literal[272000]: ...


class RuntimeRuntimeQuarantineRecordVariant1ImmutableRangeView(Protocol):
    @property
    def range_kind(self) -> Literal["transcript_entries"]: ...

    @property
    def aggregation_buffer_ids(self) -> tuple[int, ...]: ...

    @property
    def first_sequence_number(self) -> int | None: ...

    @property
    def last_sequence_number(self) -> int | None: ...


class RuntimeRuntimeQuarantineRecordVariant2ImmutableRangeView(Protocol):
    @property
    def range_kind(self) -> Literal["speaker_mapping_event"]: ...

    @property
    def mapping_event_id(self) -> str: ...


class RuntimeRuntimeQuarantineRecordVariant3ImmutableRangeView(Protocol):
    @property
    def range_kind(self) -> Literal["interaction_cursors"]: ...

    @property
    def first_cursor(self) -> int: ...

    @property
    def last_cursor(self) -> int: ...


class RuntimeRuntimeResetCommandExplicitPreferencesToDeleteItemView(Protocol):
    @property
    def key(self) -> Literal["notifications_enabled", "speaker_tag_nudges_enabled"]: ...

    @property
    def current_value(self) -> bool: ...


class RuntimeRuntimeTickVariant1PayloadView(Protocol):
    @property
    def payload_kind(self) -> Literal["user_message"] | None: ...


class RuntimeRuntimeTickVariant1SourceRefView(Protocol):
    @property
    def kind(self) -> Literal["user_message"] | None: ...


class RuntimeRuntimeTickVariant2PayloadView(Protocol):
    @property
    def payload_kind(self) -> Literal["transcript_availability"] | None: ...


class RuntimeRuntimeTickVariant2SourceRefView(Protocol):
    @property
    def kind(self) -> Literal["transcript_availability"] | None: ...


class RuntimeRuntimeTickVariant3PayloadView(Protocol):
    @property
    def payload_kind(self) -> Literal["speaker_mapping"] | None: ...


class RuntimeRuntimeTickVariant3SourceRefView(Protocol):
    @property
    def kind(self) -> Literal["speaker_mapping"] | None: ...


class RuntimeRuntimeTickVariant4PayloadView(Protocol):
    @property
    def payload_kind(self) -> Literal["interaction_window"] | None: ...


class RuntimeRuntimeTickVariant4SourceRefView(Protocol):
    @property
    def kind(self) -> Literal["interaction_window"] | None: ...


class RuntimeRuntimeTickVariant5PayloadView(Protocol):
    @property
    def payload_kind(self) -> Literal["schedule"] | None: ...


class RuntimeRuntimeTickVariant5SourceRefView(Protocol):
    @property
    def kind(self) -> Literal["schedule"] | None: ...


class RuntimeVersionView(Protocol):
    @property
    def major(self) -> Literal[1]: ...

    @property
    def minor(self) -> int: ...


class MobileChatCurrentStatusView(Protocol):
    @property
    def schema_version(self) -> MobileVersionView: ...

    @property
    def user_message_id(self) -> str: ...

    @property
    def stream_id(self) -> str: ...

    @property
    def state(
        self,
    ) -> Literal[
        "accepted", "running", "interrupted", "recovering", "completed", "failed"
    ]: ...

    @property
    def safe_display_text(self) -> str: ...

    @property
    def updated_at_ms(self) -> int: ...

    @property
    def replay_transient_progress(self) -> Literal[False]: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class MobileChatEventVariant1View(Protocol):
    @property
    def kind(self) -> Literal["final"] | None: ...

    @property
    def assistant_message_id(self) -> str | None: ...

    @property
    def final_reply_receipt_id(self) -> str | None: ...

    @property
    def ephemeral(self) -> Literal[False] | None: ...


class MobileChatEventVariant2View(Protocol):
    @property
    def kind(
        self,
    ) -> (
        Literal[
            "accepted",
            "started",
            "assistant_delta",
            "safe_status",
            "tool_started",
            "tool_progress",
            "tool_succeeded",
            "tool_failed",
            "heartbeat",
            "recovering",
        ]
        | None
    ): ...

    @property
    def assistant_message_id(self) -> None: ...

    @property
    def final_reply_receipt_id(self) -> None: ...

    @property
    def ephemeral(self) -> Literal[True] | None: ...


class MobileChatEventVariant3View(Protocol):
    @property
    def kind(self) -> Literal["interrupted", "failed"] | None: ...

    @property
    def assistant_message_id(self) -> None: ...

    @property
    def final_reply_receipt_id(self) -> None: ...

    @property
    def ephemeral(self) -> Literal[False] | None: ...


class MobileChatReconnectView(Protocol):
    @property
    def schema_version(self) -> MobileVersionView: ...

    @property
    def canonical_message_ids(self) -> tuple[str, ...]: ...

    @property
    def current_status(self) -> MobileChatCurrentStatusView: ...

    @property
    def future_events_only(self) -> Literal[True]: ...

    @property
    def outbox_pending_message_ids(self) -> tuple[str, ...]: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class MobileHomeActivationView(Protocol):
    @property
    def schema_version(self) -> MobileVersionView: ...

    @property
    def action_id(self) -> str: ...

    @property
    def source_revision(self) -> int: ...

    @property
    def expected_current_revision(self) -> int: ...

    @property
    def new_revision(self) -> int: ...

    @property
    def revalidated(self) -> Literal[True]: ...

    @property
    def navigation_changed(self) -> Literal[False]: ...

    @property
    def created_at_ms(self) -> int: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class MobileHomeHistoryView(Protocol):
    @property
    def schema_version(self) -> MobileVersionView: ...

    @property
    def current_revision(self) -> int: ...

    @property
    def retention_limit(self) -> Literal[50]: ...

    @property
    def revisions(self) -> tuple[MobileHomeRevisionView, ...]: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class MobileHomeRevisionView(Protocol):
    @property
    def schema_version(self) -> MobileVersionView: ...

    @property
    def revision(self) -> int: ...

    @property
    def parent_revision(self) -> int | None: ...

    @property
    def originating_run_id(self) -> str: ...

    @property
    def action_id(self) -> str: ...

    @property
    def reason(self) -> str: ...

    @property
    def created_at_ms(self) -> int: ...

    @property
    def state(self) -> MobileHomeStateView: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class MobileHomeStateView(Protocol):
    @property
    def schema_version(self) -> MobileVersionView: ...

    @property
    def user_id(self) -> str: ...

    @property
    def revision(self) -> int: ...

    @property
    def updated_at_ms(self) -> int: ...

    @property
    def nodes(
        self,
    ) -> tuple[
        MobileHomeNodeVariant1View
        | MobileHomeNodeVariant2View
        | MobileHomeNodeVariant3View
        | MobileHomeNodeVariant4View,
        ...,
    ]: ...

    @property
    def app_owned_chrome(
        self,
    ) -> tuple[
        Literal[
            "home.chrome.header",
            "home.banner.google-reconnect",
            "home.card.listening",
            "home.chrome.footer",
        ],
        ...,
    ]: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class MobileInteractionBatchView(Protocol):
    @property
    def schema_version(self) -> MobileVersionView: ...

    @property
    def batch_id(self) -> str: ...

    @property
    def user_id(self) -> str: ...

    @property
    def first_cursor(self) -> int: ...

    @property
    def last_cursor(self) -> int: ...

    @property
    def window_start_ms(self) -> int: ...

    @property
    def window_end_ms(self) -> int: ...

    @property
    def events(
        self,
    ) -> tuple[
        MobileInteractionEventVariant1View
        | MobileInteractionEventVariant2View
        | MobileInteractionEventVariant3View
        | MobileInteractionEventVariant4View
        | MobileInteractionEventVariant5View
        | MobileInteractionEventVariant6View
        | MobileInteractionEventVariant7View
        | MobileInteractionEventVariant8View
        | MobileInteractionEventVariant9View
        | MobileInteractionEventVariant10View
        | MobileInteractionEventVariant11View
        | MobileInteractionEventVariant12View
        | MobileInteractionEventVariant13View
        | MobileInteractionEventVariant14View
        | MobileInteractionEventVariant15View,
        ...,
    ]: ...

    @property
    def delivery_attempt(self) -> int: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class MobileInteractionDeliveryAckView(Protocol):
    @property
    def schema_version(self) -> MobileVersionView: ...

    @property
    def ack_id(self) -> str: ...

    @property
    def batch_id(self) -> str: ...

    @property
    def ack_cursor(self) -> int: ...

    @property
    def durably_stored_event_ids(self) -> tuple[str, ...]: ...

    @property
    def model_processed(self) -> Literal[False]: ...

    @property
    def acknowledged_at_ms(self) -> int: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class MobileInteractionEventVariant10View(Protocol):
    @property
    def kind(self) -> Literal["notes_action"] | None: ...

    @property
    def safe_payload(
        self,
    ) -> MobileMobileInteractionEventVariant10SafePayloadView | None: ...


class MobileInteractionEventVariant11View(Protocol):
    @property
    def kind(self) -> Literal["task_action"] | None: ...

    @property
    def safe_payload(
        self,
    ) -> MobileMobileInteractionEventVariant11SafePayloadView | None: ...


class MobileInteractionEventVariant12View(Protocol):
    @property
    def kind(self) -> Literal["gift_action"] | None: ...

    @property
    def safe_payload(
        self,
    ) -> MobileMobileInteractionEventVariant12SafePayloadView | None: ...


class MobileInteractionEventVariant13View(Protocol):
    @property
    def kind(self) -> Literal["transcript_action"] | None: ...

    @property
    def safe_payload(
        self,
    ) -> MobileMobileInteractionEventVariant13SafePayloadView | None: ...


class MobileInteractionEventVariant14View(Protocol):
    @property
    def kind(self) -> Literal["voice_fingerprint_action"] | None: ...

    @property
    def safe_payload(
        self,
    ) -> MobileMobileInteractionEventVariant14SafePayloadView | None: ...


class MobileInteractionEventVariant15View(Protocol):
    @property
    def kind(self) -> Literal["account_action"] | None: ...

    @property
    def safe_payload(
        self,
    ) -> MobileMobileInteractionEventVariant15SafePayloadView | None: ...


class MobileInteractionEventVariant1View(Protocol):
    @property
    def kind(self) -> Literal["navigation_selection"] | None: ...

    @property
    def safe_payload(
        self,
    ) -> MobileMobileInteractionEventVariant1SafePayloadView | None: ...


class MobileInteractionEventVariant2View(Protocol):
    @property
    def kind(self) -> Literal["home_activation"] | None: ...

    @property
    def safe_payload(
        self,
    ) -> MobileMobileInteractionEventVariant2SafePayloadView | None: ...


class MobileInteractionEventVariant3View(Protocol):
    @property
    def kind(self) -> Literal["chat_submission"] | None: ...

    @property
    def safe_payload(
        self,
    ) -> MobileMobileInteractionEventVariant3SafePayloadView | None: ...


class MobileInteractionEventVariant4View(Protocol):
    @property
    def kind(self) -> Literal["speaker_action"] | None: ...

    @property
    def safe_payload(
        self,
    ) -> MobileMobileInteractionEventVariant4SafePayloadView | None: ...


class MobileInteractionEventVariant5View(Protocol):
    @property
    def kind(self) -> Literal["integration_change"] | None: ...

    @property
    def safe_payload(
        self,
    ) -> MobileMobileInteractionEventVariant5SafePayloadView | None: ...


class MobileInteractionEventVariant6View(Protocol):
    @property
    def kind(self) -> Literal["recording_control"] | None: ...

    @property
    def safe_payload(
        self,
    ) -> MobileMobileInteractionEventVariant6SafePayloadView | None: ...


class MobileInteractionEventVariant7View(Protocol):
    @property
    def kind(self) -> Literal["notification_action"] | None: ...

    @property
    def safe_payload(
        self,
    ) -> MobileMobileInteractionEventVariant7SafePayloadView | None: ...


class MobileInteractionEventVariant8View(Protocol):
    @property
    def kind(self) -> Literal["settings_change"] | None: ...

    @property
    def safe_payload(
        self,
    ) -> MobileMobileInteractionEventVariant8SafePayloadView | None: ...


class MobileInteractionEventVariant9View(Protocol):
    @property
    def kind(self) -> Literal["permission_action"] | None: ...

    @property
    def safe_payload(
        self,
    ) -> MobileMobileInteractionEventVariant9SafePayloadView | None: ...


class MobileMobileChatOutboxVariant1View(Protocol):
    @property
    def status(self) -> Literal["waiting_for_connection", "submitting"] | None: ...

    @property
    def backend_submission_id(self) -> None: ...

    @property
    def queue_receipt_id(self) -> None: ...

    @property
    def cancellable(self) -> Literal[True] | None: ...


class MobileMobileChatOutboxVariant2View(Protocol):
    @property
    def status(self) -> Literal["submitted"] | None: ...

    @property
    def backend_submission_id(self) -> str | None: ...

    @property
    def queue_receipt_id(self) -> str | None: ...

    @property
    def cancellable(self) -> Literal[False] | None: ...


class MobileMobileChatOutboxVariant3View(Protocol):
    @property
    def status(self) -> Literal["cancelled"] | None: ...

    @property
    def backend_submission_id(self) -> None: ...

    @property
    def queue_receipt_id(self) -> None: ...

    @property
    def cancellable(self) -> Literal[False] | None: ...


class MobileNavigationIntentView(Protocol):
    @property
    def schema_version(self) -> MobileVersionView: ...

    @property
    def intent_id(self) -> str: ...

    @property
    def destination_id(
        self,
    ) -> Literal[
        "route.home",
        "route.chat",
        "route.connectors",
        "route.speakers-list",
        "route.notification-settings",
        "route.permission-other",
        "route.live-transcript",
        "route.profile",
    ]: ...

    @property
    def parameters(self) -> MobileMobileNavigationIntentParametersView: ...

    @property
    def activation_source(self) -> Literal["home_tap", "os_notification_tap"]: ...

    @property
    def user_action_id(self) -> str: ...

    @property
    def created_at_ms(self) -> int: ...

    @property
    def force_current_screen(self) -> Literal[False]: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class MobileNotificationIntentVariant1View(Protocol):
    @property
    def kind(self) -> Literal["background_message_push"] | None: ...

    @property
    def persisted_message_id(self) -> str | None: ...

    @property
    def navigation_template(self) -> Literal["route.chat"] | None: ...

    @property
    def push_required_for_background_message(self) -> Literal[True] | None: ...


class MobileNotificationIntentVariant2View(Protocol):
    @property
    def kind(self) -> Literal["standalone_notification"] | None: ...

    @property
    def persisted_message_id(self) -> None: ...

    @property
    def push_required_for_background_message(self) -> Literal[True] | None: ...


class MobileNotificationOutcomeVariant1View(Protocol):
    @property
    def communication_kind(self) -> Literal["background_message"] | None: ...

    @property
    def outcome(
        self,
    ) -> (
        Literal["accepted", "skipped_permission_disabled", "failed_terminal"] | None
    ): ...

    @property
    def persisted_message_id(self) -> str | None: ...

    @property
    def allowance_consumed(self) -> Literal[True] | None: ...


class MobileNotificationOutcomeVariant2View(Protocol):
    @property
    def communication_kind(self) -> Literal["standalone_notification"] | None: ...

    @property
    def outcome(self) -> Literal["accepted"] | None: ...

    @property
    def persisted_message_id(self) -> None: ...

    @property
    def allowance_consumed(self) -> Literal[True] | None: ...


class MobileNotificationOutcomeVariant3View(Protocol):
    @property
    def communication_kind(self) -> Literal["standalone_notification"] | None: ...

    @property
    def outcome(
        self,
    ) -> (
        Literal["permission_required", "capability_disabled", "failed_terminal"] | None
    ): ...

    @property
    def persisted_message_id(self) -> None: ...

    @property
    def allowance_consumed(self) -> Literal[False] | None: ...


class MobileNotificationPermissionView(Protocol):
    @property
    def schema_version(self) -> MobileVersionView: ...

    @property
    def user_preference(self) -> Literal["enabled", "disabled"]: ...

    @property
    def os_permission(
        self,
    ) -> Literal[
        "authorized", "denied", "not_determined", "provisional", "unknown"
    ]: ...

    @property
    def last_permission_ask_at_ms(self) -> int | None: ...

    @property
    def last_permission_ask_topic_id(self) -> str | None: ...

    @property
    def observed_at_ms(self) -> int: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class MobileHomeNodeVariant1View(Protocol):
    @property
    def component_id(self) -> Literal["home.hero.greeting"] | None: ...

    @property
    def navigation_template(self) -> None: ...

    @property
    def content(self) -> MobileMobileHomeNodeVariant1ContentView | None: ...


class MobileHomeNodeVariant2View(Protocol):
    @property
    def component_id(self) -> Literal["home.action.what-did-i-miss"] | None: ...

    @property
    def navigation_template(self) -> Literal["route.chat"] | None: ...

    @property
    def content(self) -> MobileMobileHomeNodeVariant2ContentView | None: ...


class MobileHomeNodeVariant3View(Protocol):
    @property
    def component_id(self) -> Literal["home.card.connectors"] | None: ...

    @property
    def navigation_template(self) -> Literal["route.connectors"] | None: ...

    @property
    def content(self) -> MobileMobileHomeNodeVariant3ContentView | None: ...


class MobileHomeNodeVariant4View(Protocol):
    @property
    def component_id(self) -> Literal["home.card.people"] | None: ...

    @property
    def navigation_template(self) -> Literal["route.speakers-list"] | None: ...

    @property
    def content(self) -> MobileMobileHomeNodeVariant4ContentView | None: ...


class MobileMobileInteractionEventVariant10SafePayloadView(Protocol):
    @property
    def action(
        self,
    ) -> (
        Literal[
            "open",
            "share_request",
            "copy_request",
            "edit_request",
            "calendar_open",
            "date_select",
            "retry",
            "return_today",
            "transcript_open",
        ]
        | None
    ): ...


class MobileMobileInteractionEventVariant11SafePayloadView(Protocol):
    @property
    def action(
        self,
    ) -> (
        Literal["prepare", "finish", "undo", "flush", "retry", "error", "dismiss"]
        | None
    ): ...


class MobileMobileInteractionEventVariant12SafePayloadView(Protocol):
    @property
    def action(
        self,
    ) -> (
        Literal["impression", "open_page", "share_request", "save_request", "dismiss"]
        | None
    ): ...


class MobileMobileInteractionEventVariant13SafePayloadView(Protocol):
    @property
    def action(
        self,
    ) -> Literal["refresh", "retry", "open_speaker", "share_request"] | None: ...


class MobileMobileInteractionEventVariant14SafePayloadView(Protocol):
    @property
    def action(
        self,
    ) -> Literal["show", "start", "retry", "skip", "continue"] | None: ...


class MobileMobileInteractionEventVariant15SafePayloadView(Protocol):
    @property
    def action(
        self,
    ) -> (
        Literal["logout_request", "logout_confirm", "delete_request", "delete_confirm"]
        | None
    ): ...


class MobileMobileInteractionEventVariant1SafePayloadView(Protocol):
    @property
    def action(
        self,
    ) -> (
        Literal[
            "route_select",
            "tab_select",
            "widget_open",
            "shortcut_open",
            "live_activity_open",
            "universal_link_open",
        ]
        | None
    ): ...


class MobileMobileInteractionEventVariant2SafePayloadView(Protocol):
    @property
    def action(
        self,
    ) -> (
        Literal["component_tap", "last_good_fallback", "invalid_state_diagnostic"]
        | None
    ): ...


class MobileMobileInteractionEventVariant3SafePayloadView(Protocol):
    @property
    def action(
        self,
    ) -> (
        Literal["send_accepted", "offline_retry", "pre_submit_cancel", "report_message"]
        | None
    ): ...


class MobileMobileInteractionEventVariant4SafePayloadView(Protocol):
    @property
    def action(
        self,
    ) -> (
        Literal[
            "tag",
            "rename",
            "merge",
            "unlink",
            "archive",
            "discard_sample",
            "sample_play",
            "sample_pause",
        ]
        | None
    ): ...


class MobileMobileInteractionEventVariant5SafePayloadView(Protocol):
    @property
    def action(
        self,
    ) -> Literal["connector_add", "connector_remove", "connector_status"] | None: ...


class MobileMobileInteractionEventVariant6SafePayloadView(Protocol):
    @property
    def action(
        self,
    ) -> (
        Literal["ambient_start", "ambient_pause", "ambient_resume", "ambient_stop"]
        | None
    ): ...


class MobileMobileInteractionEventVariant7SafePayloadView(Protocol):
    @property
    def action(self) -> Literal["open", "dismiss"] | None: ...


class MobileMobileInteractionEventVariant8SafePayloadView(Protocol):
    @property
    def action(self) -> Literal["closed_key_toggle"] | None: ...


class MobileMobileInteractionEventVariant9SafePayloadView(Protocol):
    @property
    def action(
        self,
    ) -> Literal["show", "request", "continue", "open_settings", "outcome"] | None: ...


class MobileMobileNavigationIntentParametersView(Protocol):
    @property
    def message_id(self) -> str | None: ...

    @property
    def open_add_sheet(self) -> bool | None: ...


class MobileVersionView(Protocol):
    @property
    def major(self) -> Literal[1]: ...

    @property
    def minor(self) -> int: ...


class MobileMobileHomeNodeVariant1ContentView(Protocol):
    @property
    def count(self) -> None: ...

    @property
    def action_key(self) -> None: ...


class MobileMobileHomeNodeVariant2ContentView(Protocol):
    @property
    def count(self) -> None: ...

    @property
    def action_key(self) -> Literal["open_chat"] | None: ...


class MobileMobileHomeNodeVariant3ContentView(Protocol):
    @property
    def count(self) -> int | None: ...

    @property
    def action_key(self) -> Literal["open_connectors"] | None: ...


class MobileMobileHomeNodeVariant4ContentView(Protocol):
    @property
    def count(self) -> int | None: ...

    @property
    def action_key(self) -> Literal["open_speakers"] | None: ...


class DataplaneInputGapView(Protocol):
    @property
    def schema_version(self) -> DataplaneVersionView: ...

    @property
    def gap_id(self) -> str: ...

    @property
    def source_kind(
        self,
    ) -> Literal["transcript", "speaker_mapping", "interaction"]: ...

    @property
    def source_identity(self) -> str: ...

    @property
    def quarantine_id(self) -> str: ...

    @property
    def normal_cursor_advanced(self) -> Literal[True]: ...

    @property
    def reason(self) -> Literal["attempts_exhausted"]: ...

    @property
    def recorded_at_ms(self) -> int: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class DataplaneSpeakerCursorOutcomeVariant1View(Protocol):
    @property
    def outcome(self) -> Literal["acknowledged"] | None: ...

    @property
    def quarantine_id(self) -> None: ...


class DataplaneSpeakerCursorOutcomeVariant2View(Protocol):
    @property
    def outcome(self) -> Literal["quarantined_and_advanced"] | None: ...

    @property
    def quarantine_id(self) -> str | None: ...


class DataplaneSpeakerMappingEventView(Protocol):
    @property
    def schema_version(self) -> DataplaneVersionView: ...

    @property
    def event_id(self) -> str: ...

    @property
    def user_id(self) -> str: ...

    @property
    def cursor(self) -> int: ...

    @property
    def kind(self) -> Literal["rename", "merge"]: ...

    @property
    def source_speaker_ids(self) -> tuple[str, ...]: ...

    @property
    def canonical_speaker_id(self) -> str: ...

    @property
    def old_name(self) -> str | None: ...

    @property
    def new_name(self) -> str | None: ...

    @property
    def changed_at_ms(self) -> int: ...

    @property
    def transcript_text_included(self) -> Literal[False]: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class DataplaneTranscriptAckView(Protocol):
    @property
    def schema_version(self) -> DataplaneVersionView: ...

    @property
    def ack_id(self) -> str: ...

    @property
    def claim_id(self) -> str: ...

    @property
    def run_id(self) -> str: ...

    @property
    def memory_version(self) -> str: ...

    @property
    def acknowledged_at_ms(self) -> int: ...

    @property
    def deleted_buffer_entry_ids(self) -> tuple[int, ...]: ...

    @property
    def durable_receipt_written(self) -> Literal[True]: ...

    @property
    def canonical_transcript_retained(self) -> Literal[True]: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class DataplaneTranscriptCanonicalLookupView(Protocol):
    @property
    def schema_version(self) -> DataplaneVersionView: ...

    @property
    def sequence_number(self) -> int: ...

    @property
    def transcript(self) -> str: ...

    @property
    def segments(
        self,
    ) -> tuple[DataplaneSegmentVariant1View | DataplaneSegmentVariant2View, ...]: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class DataplaneTranscriptClaimRequestView(Protocol):
    @property
    def schema_version(self) -> DataplaneVersionView: ...

    @property
    def claim_request_id(self) -> str: ...

    @property
    def lease_owner(self) -> str: ...

    @property
    def now_ms(self) -> int: ...

    @property
    def lease_duration_ms(self) -> Literal[600000]: ...

    @property
    def caps(self) -> DataplaneTranscriptClaimCapsView: ...

    @property
    def eligibility(
        self,
    ) -> DataplaneDataplaneTranscriptClaimRequestEligibilityView: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class DataplaneTranscriptClaimVariant1View(Protocol):
    @property
    def claim_state(self) -> Literal["claimed"] | None: ...

    @property
    def acknowledged_at_ms(self) -> None: ...

    @property
    def released_at_ms(self) -> None: ...

    @property
    def release_reason(self) -> None: ...


class DataplaneTranscriptClaimVariant2View(Protocol):
    @property
    def claim_state(self) -> Literal["acknowledged"] | None: ...

    @property
    def acknowledged_at_ms(self) -> int | None: ...

    @property
    def released_at_ms(self) -> None: ...

    @property
    def release_reason(self) -> None: ...


class DataplaneTranscriptClaimVariant3View(Protocol):
    @property
    def claim_state(self) -> Literal["released"] | None: ...

    @property
    def acknowledged_at_ms(self) -> None: ...

    @property
    def released_at_ms(self) -> int | None: ...

    @property
    def release_reason(self) -> str | None: ...


class DataplaneTranscriptLeaseRenewRequestView(Protocol):
    @property
    def schema_version(self) -> DataplaneVersionView: ...

    @property
    def renewal_request_id(self) -> str: ...

    @property
    def claim_id(self) -> str: ...

    @property
    def lease_owner(self) -> str: ...

    @property
    def prior_lease_expires_at_ms(self) -> int: ...

    @property
    def new_lease_expires_at_ms(self) -> int: ...

    @property
    def idempotency_key(self) -> str: ...

    @property
    def requested_at_ms(self) -> int: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class DataplaneTranscriptLeaseRenewResultView(Protocol):
    @property
    def schema_version(self) -> DataplaneVersionView: ...

    @property
    def renewal_request_id(self) -> str: ...

    @property
    def claim_id(self) -> str: ...

    @property
    def lease_owner(self) -> str: ...

    @property
    def prior_lease_expires_at_ms(self) -> int: ...

    @property
    def new_lease_expires_at_ms(self) -> int: ...

    @property
    def idempotency_key(self) -> str: ...

    @property
    def outcome(self) -> Literal["renewed", "already_renewed"]: ...

    @property
    def renewed_at_ms(self) -> int: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class DataplaneTranscriptReclaimRequestView(Protocol):
    @property
    def schema_version(self) -> DataplaneVersionView: ...

    @property
    def reclaim_request_id(self) -> str: ...

    @property
    def now_ms(self) -> int: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class DataplaneTranscriptReclaimResultVariant1View(Protocol):
    @property
    def outcome(self) -> Literal["empty"] | None: ...

    @property
    def released_claim_ids(self) -> FrozenJSONValue | None: ...

    @property
    def released_entry_count(self) -> Literal[0] | None: ...


class DataplaneTranscriptReclaimResultVariant2View(Protocol):
    @property
    def outcome(self) -> Literal["reclaimed_expired"] | None: ...

    @property
    def released_claim_ids(self) -> FrozenJSONValue | None: ...

    @property
    def released_entry_count(self) -> FrozenJSONValue | None: ...


class DataplaneTranscriptReleaseView(Protocol):
    @property
    def schema_version(self) -> DataplaneVersionView: ...

    @property
    def claim_id(self) -> str: ...

    @property
    def reason(self) -> str: ...

    @property
    def released_at_ms(self) -> int: ...

    @property
    def input_retained(self) -> Literal[True]: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class DataplaneDataplaneTranscriptClaimRequestEligibilityView(Protocol):
    @property
    def source_type(self) -> Literal["audio"]: ...

    @property
    def status_filter(self) -> Literal[None]: ...

    @property
    def unknown_speaker_eligible(self) -> Literal[True]: ...

    @property
    def excluded_source_types(
        self,
    ) -> tuple[Literal["audio_fast", "non_audio"], ...]: ...


class DataplaneSegmentVariant1View(Protocol):
    @property
    def type(self) -> Literal["speech"] | None: ...

    @property
    def speaker(self) -> Mapping[str, FrozenJSONValue] | None: ...


class DataplaneSegmentVariant2View(Protocol):
    @property
    def type(self) -> Literal["audio_event"] | None: ...

    @property
    def speaker(self) -> None: ...


class DataplaneTranscriptClaimCapsView(Protocol):
    @property
    def target_source_duration_ms(self) -> Literal[600000]: ...

    @property
    def target_transcript_tokens(self) -> Literal[8000]: ...

    @property
    def absolute_window_tokens(self) -> Literal[200000]: ...

    @property
    def max_entries(self) -> int | None: ...

    @property
    def continuation_cursor(
        self,
    ) -> None | DataplaneTranscriptContinuationCursorView: ...


class DataplaneVersionView(Protocol):
    @property
    def major(self) -> Literal[1]: ...

    @property
    def minor(self) -> int: ...


class DataplaneTranscriptContinuationCursorView(Protocol):
    @property
    def aggregation_buffer_id(self) -> int: ...

    @property
    def provenance(self) -> str: ...

    @property
    def next_segment_ordinal(self) -> int: ...


class PolicyPreferencesView(Protocol):
    @property
    def schema_version(self) -> PolicyVersionView: ...

    @property
    def user_id(self) -> str: ...

    @property
    def revision(self) -> int: ...

    @property
    def narrow_preferences(self) -> tuple[PolicyPreferenceView, ...]: ...

    @property
    def non_disableable_capabilities(
        self,
    ) -> tuple[
        Literal[
            "background_inference",
            "home_mutation",
            "schedule_creation",
            "proactive_chat",
        ],
        ...,
    ]: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class PolicyScheduleView(Protocol):
    @property
    def schema_version(self) -> PolicyVersionView: ...

    @property
    def schedule_id(self) -> str: ...

    @property
    def user_id(self) -> str: ...

    @property
    def due_at_ms(self) -> int: ...

    @property
    def created_at_ms(self) -> int: ...

    @property
    def status(
        self,
    ) -> Literal["active", "enqueued", "cancelled", "completed", "failed_terminal"]: ...

    @property
    def reason(self) -> str: ...

    @property
    def originating_run_id(self) -> str: ...

    @property
    def originating_action_id(self) -> str: ...

    @property
    def attempt_ordinal(self) -> int: ...

    @property
    def promoted_to_p1_at_ms(self) -> int | None: ...

    @property
    def extensions(self) -> Mapping[str, FrozenJSONValue]: ...


class PolicyPreferenceView(Protocol):
    @property
    def key(self) -> Literal["notifications_enabled", "speaker_tag_nudges_enabled"]: ...

    @property
    def value(self) -> bool: ...

    @property
    def switchable_by_agent_on_explicit_user_request(self) -> Literal[True]: ...

    @property
    def authorizing_message_id(self) -> str: ...

    @property
    def updated_at_ms(self) -> int: ...


class PolicyVersionView(Protocol):
    @property
    def major(self) -> Literal[1]: ...

    @property
    def minor(self) -> int: ...
